on: [push]

name: Clippy

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -W clippy::cargo -W clippy::pedantic
